language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - sqlite

matrix:
  include:
    - php: 7.1
  fast_finish: true

install:
  - composer update --prefer-dist

before_script:
  - php Tests/Fixtures/bin/console doctrine:database:drop --env=starter_kit_test --force
  - php Tests/Fixtures/bin/console doctrine:database:create --env=starter_kit_test
  - php Tests/Fixtures/bin/console doctrine:schema:update --env=starter_kit_test --force
  - php Tests/Fixtures/bin/console doctrine:fixtures:load --env=starter_kit_test --no-interaction --fixtures=DataFixtures/ORM/


script:
    - php vendor/bin/phpunit  --exclude-group exclude_travis  --coverage-clover=coverage.xml

after_success:
  - travis_retry  bash <(curl -s https://codecov.io/bash)
