language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - sqlite
  - redis

matrix:
  include:
    - php: 7.1
  fast_finish: true

before_install:
  - git clone https://github.com/phptuts/starter-bundle-example.git
  - cd starter-bundle-example

install:
  - composer update --prefer-dist

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - mkdir var/jwt
  - cp scripts/private.pem var/jwt/private.pem
  - cp scripts/public.pem var/jwt/public.pem
  - php bin/console doctrine:database:drop --env=starter_kit_test --force
  - php bin/console doctrine:database:create --env=starter_kit_test
  - php bin/console doctrine:schema:update --env=starter_kit_test --force
  - php bin/console doctrine:fixtures:load --env=starter_kit_test --no-interaction --fixtures=vendor/start-kit-symfony/start-bundle/DataFixtures/ORM/


script:
    - php bin/phpunit -c vendor/start-kit-symfony/start-bundle/ --exclude-group exclude_travis --coverage-clover build/logs/clover.xml
    - CODECLIMATE_REPO_TOKEN=f04bc19d37067f93b0cc455da14be2136711b76635fc3267f7d5bd2fda2c2702 ./vendor/bin/test-reporter

after_success:
  - travis_retry php php-coveralls.phar -v
