language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - sqlite

matrix:
  include:
    - php: 7.1
  fast_finish: true

install:
  - composer update --prefer-dist

before_script:
  - php tests/Fixtures/bin/console doctrine:database:drop --env=test --force
  - php tests/Fixtures/bin/console doctrine:database:create --env=test
  - php tests/Fixtures/bin/console doctrine:schema:update --env=test --force
  - php tests/Fixtures/bin/console doctrine:fixtures:load --env=test --no-interaction


script:
    - vendor/bin/simple-phpunit  --exclude-group exclude_travis  --coverage-clover=coverage.xml --verbose

after_success:
  - travis_retry  bash <(curl -s https://codecov.io/bash)
