services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $userClass: '%starter_kit_start.user_class%'
            $slackSecret: '%starter_kit_start.slack_client_secret%'
            $slackClientId: '%starter_kit_start.slack_client_id%'

            $passPhrase: '%starter_kit_start.jws_pass_phrase%'
            $authTokenTTL: '%starter_kit_start.jws_ttl%'
            $refreshTokenTTL: '%starter_kit_start.refresh_token_ttl%'

            $projectDir: '%kernel.project_dir%'

            $env: '%kernel.environment%'
            $bucketName: '%starter_kit_start.aws_s3_bucket_name%'

            $loginPath: '%starter_kit_start.login_url%'

            $fbAppId: '%starter_kit_start.facebook_app_id%'
            $fbAppSecret: '%starter_kit_start.facebook_app_secret%'
            $fbApiVersion: '%starter_kit_start.facebook_api_version%'

            $googleClientId: '%starter_kit_start.google_client_id%'

            $awsRegion: '%starter_kit_start.aws_region%'
            $awsKey: '%starter_kit_start.aws_key%'
            $awsSecret: '%starter_kit_start.aws_secret%'
            $awsApiVersion: '%starter_kit_start.aws_api_version%'
            # Concrete Implementations



    StarterKit\StartBundle\:
        resource: '../../'
        exclude: '../../{Entity,Migrations,Controller,Model}'

    StarterKit\StartBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # Clients
    GuzzleHttp\Client:
        class: GuzzleHttp\Client


    # Services
    StarterKit\StartBundle\Service\AuthTokenServiceInterface: '@StarterKit\StartBundle\Service\JWSTokenService'
    StarterKit\StartBundle\Service\UserServiceInterface: '@StarterKit\StartBundle\Service\UserService'
    StarterKit\StartBundle\Service\AuthResponseServiceInterface: '@StarterKit\StartBundle\Service\AuthResponseService'
    StarterKit\StartBundle\Service\FormSerializerInterface: '@StarterKit\StartBundle\Service\FormSerializer'
    StarterKit\StartBundle\Service\S3ServiceInterface: '@StarterKit\StartBundle\Service\S3Service'

    #Transformer
    StarterKit\StartBundle\Form\DataTransformer\UserEmailTransformerInterface: '@StarterKit\StartBundle\Form\DataTransformer\UserEmailTransformer'

    # Providers
    StarterKit\StartBundle\Security\Provider\EmailProviderInterface: '@StarterKit\StartBundle\Security\Provider\EmailProvider'
    StarterKit\StartBundle\Security\Provider\FacebookProviderInterface: '@StarterKit\StartBundle\Security\Provider\FacebookProvider'
    StarterKit\StartBundle\Security\Provider\GoogleProviderInterface: '@StarterKit\StartBundle\Security\Provider\GoogleProvider'
    StarterKit\StartBundle\Security\Provider\TokenProviderInterface: '@StarterKit\StartBundle\Security\Provider\TokenProvider'
    StarterKit\StartBundle\Security\Provider\RefreshTokenProviderInterface: '@StarterKit\StartBundle\Security\Provider\RefreshTokenProvider'
    StarterKit\StartBundle\Security\Provider\SlackProviderInterface: '@StarterKit\StartBundle\Security\Provider\SlackProvider'

    # Guards
    StarterKit\StartBundle\Security\Guard\OAuth\OAuthGuardInterface:  '@StarterKit\StartBundle\Security\Guard\OAuth\OAuthGuard'
    StarterKit\StartBundle\Security\Guard\Login\AccessTokenGuardInterface: '@StarterKit\StartBundle\Security\Guard\Login\AccessTokenGuard'
    StarterKit\StartBundle\Security\Guard\Login\EmailGuardInterface: '@StarterKit\StartBundle\Security\Guard\Login\EmailGuard'
    StarterKit\StartBundle\Security\Guard\StateLess\ApiGuardInterface: '@StarterKit\StartBundle\Security\Guard\StateLess\ApiGuard'
    StarterKit\StartBundle\Security\Guard\StateLess\WebsiteGuardInterface: '@StarterKit\StartBundle\Security\Guard\StateLess\WebsiteGuard'

    # Factories
    StarterKit\StartBundle\Factory\FaceBookClientFactoryInterface: '@StarterKit\StartBundle\Factory\FaceBookClientFactory'
    StarterKit\StartBundle\Factory\GoogleClientFactoryInterface: '@StarterKit\StartBundle\Factory\GoogleClientFactory'
    StarterKit\StartBundle\S3ClientFactoryInterface: '@StarterKit\StartBundle\S3ClientFactory'

